### ISSUE TITLE
Map area clipping issue

### ISSUE THREAD

**Issue by sxwee** [chenyuqi990215/RNTrajRec#7]
I followed your processing procedure to handle the Porto dataset, but when I ran it on RNTrajRec, I encountered a KeyError. It seems that the road segments corresponding to the trajectory points obtained using HMM are not within the specified area of the Porto road network (Not belong to the valid edge set). Have you encountered this situation before? How should I handle this?
Error Info:
```
Traceback (most recent call last):
  File "multi_main.py", line 244, in <module>
    train_dataset = Dataset(rn, traj_root, mbr, args, 'train')
  File "/xxx/RNTrajRec-master/dataset.py", line 41, in __init__
    self.get_data(trajs_dir, parameters.win_size, parameters.ds_type, parameters.keep_ratio)
  File "/xxx/RNTrajRec-master/dataset.py", line 117, in get_data
    keep_ratio=1)
  File "/xxx/RNTrajRec-master/dataset.py", line 164, in parse_traj
    mm_gps_seq, mm_eids, mm_rates = self.get_trg_seq(tmp_pt_list)
  File "/xxx/RNTrajRec-master/dataset.py", line 240, in get_trg_seq
    mm_eids.append([self.rn.valid_edge_one[candi_pt.eid]])  # keep the same format as seq
KeyError: 8988
```
Furthermore, I'm curious why you chose the area (41.111975, -8.667057, 41.177462, -8.585305)? Is it determined based on the latitude and longitude of the trajectory points in the training, validation, and test sets?
I look forward to receiving your assistance!

**Comment by chenyuqi990215** [comment]
The area chosen contains most of the trajectories. As we mentioned in the paper, we only keep the urban area for training to save memory costs.

The issue occurs since road segment #8988 does not fall inside the area. You can either remove these trajectories from your training dataset or revise the training area in `multi_main.py` in case you have a GPU with enough memory.

**Comment by sxwee** [comment]
Thank you for your advice. I have resolved the previous issues, but now I have encountered another bug. When I train the model, the following assertion throws a new error:
```python
if not (output == hidden).all():
    import pdb
    pdb.set_trace()
assert (output == hidden).all()
```
Do you know why this error occurs?

**Comment by chenyuqi990215** [comment]
maybe the network contains NAN outputs, you can check where the NAN comes from.

**Comment by sxwee** [comment]
I have followed your data preprocessing procedure as outlined below:

```
raw GPS trajectories(A)
A---------interpolate_trajectory.py-------->B
A---------hmm.py---------project_trajectory.py--------->C---------epsilon_trajectory.py--------->D
B as input, D as output
```

However, I have noticed that there is a significant difference in the GPS coordinates between the trajectory points in `B` and `D`. Is this considered normal?
![diff](https://github.com/chenyuqi990215/RNTrajRec/assets/49050326/0f9193b3-3db1-4da8-90a4-d3ed69839d19)


Furthermore, I have also utilized the `tptk` module to clean and filter the trajectories. Is this step necessary?

**Comment by customtiy13** [comment]
> Thank you for your advice. I have resolved the previous issues, but now I have encountered another bug. When I train the model, the following assertion throws a new error:
> 
> ```python
> if not (output == hidden).all():
>     import pdb
>     pdb.set_trace()
> assert (output == hidden).all()
> ```
> 
> Do you know why this error occurs?

I have encountered the same error. I printed the output, and it's all Nan. Did you found the solution yet?

**Comment by chenyuqi990215** [comment]
Please check the following things:

1. Replace `search_dist` in `multi_main.py` Line 135 with a large enough value to see if the NAN still occurs. If NAN is resolved, then it is caused by improper `search_dist`. Please set the parameter to the largest possible distance error between the input GPS point and the target road segment.
2. Check where the NAN comes from, does the input contain NAN, or do network parameters contain NAN? 

We are glad to dig into the issue with you guys.
